# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    servlet:
        context-path: /jiantouMinioWebDemo

spring:
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 500MB
            max-file-size: 500MB
            max-request-size: 500MB
    minio:
        url: http://127.0.0.1:9000
        bucket: test
        access-key: minioadmin
        secret-key: minioadmin
        expiration-seconds: 6

